### ISSUE TITLE
Implement a way for a stat to go away?

### ISSUE THREAD

**Issue by MFarejowicz** [jynnie/onionvale#9]
When you have 0 of an item, I believe the item line disappears from your inventory on the next page load. It would be cool if there was a way to do this with stats as well, to avoid clutter

**Comment by jynnie** [comment]
Hmm, my thoughts on this are that perhaps we want to know that you have 0/10 Charisma. Sometimes knowing you don't have any of a stat anymore is useful (like no more armor). Perhaps, a solution is hiding on client side with local storage memory.

**Comment by jynnie** [comment]
Or perhaps hide stat for when max becomes 0?

**Comment by MFarejowicz** [comment]
Yeah I meant the latter. It probably won't happen often that a stat becomes irrelevant, but if it does it would be nice if setting the max to zero (or some other key value) made it disappear? idk

**Comment by jynnie** [comment]
Feature has now been implemented
